image:
  file: .gitpod.Dockerfile

tasks:
  - init: 'echo "TODO: Replace with init/build command"'
    command: set -o vi

vscode:
  extensions:
    - axetroy.vscode-deno@3.7.0:YlA2jgY/k6sHhu6khQB+gw==

